CREATE SEQUENCE SEQ_SEMAFORO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE TB_SEMAFORO (
  ID INTEGER DEFAULT SEQ_SEMAFORO.NEXTVAL NOT NULL,
  LOCALIZACAO VARCHAR2(255) NOT NULL,
  ESTADO_ATUAL VARCHAR2(255),
  TEMPO_VERDE INTEGER,
  TEMPO_VERMELHO INTEGER,
  CONDICOES_CLIMATICAS VARCHAR2(255),
  ULTIMA_ATUALIZACAO TIMESTAMP
);