CREATE SEQUENCE SEQ_TRAFEGO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE TB_TRAFEGO (
  ID INTEGER DEFAULT SEQ_TRAFEGO.NEXTVAL NOT NULL,
  DATA_HORA TIMESTAMP,
  LOCALIZACAO VARCHAR2(255) NOT NULL,
  QUANTIDADE_VEICULO NUMBER(10,0),
  VELOCIDADE_VEICULO NUMBER(15,2),
  CONGESTIONAMENTO NUMBER(1) CHECK (CONGESTIONAMENTO IN (0, 1))
);